language: python
 
python:
    - "2.7"

node_js: "8"


install:
    - pip install tsfresh==0.11.1
    - pip install django==1.11.13
    - pip install pylint
    - pip install mysql-python
    - pip install scikit-learn
    - npm install

services:
  - mysql
  
script:
    - export PATH=./node_modules/.bin:$PATH
    - commitlint-travis
    - make test
